### ISSUE TITLE
Resolve conflicts in requirements.tx

### ISSUE THREAD

**Issue by BiElisa** [hydro-7/python_inter_rivercatchment#8]
https://github.com/hydro-7/python_inter_rivercatchment/blob/4dcee4046b0024818864fb1196e9ece1027f8ffe/requirements.txt#L1

You need to resolve the conflicts in the requirements.txt file.
In fact, at the moment, there are lines with ">>>>" and "<<<<" that create problems.

**Comment by maureenjcohen** [comment]
Resolved now
